# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions

name: Continuous Deployment

on: release

jobs:
  continuous-integration:
    name: Ubuntu (Latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Deploy
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy