name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Testing Web-Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Update NPM
        run: npm install -g npm@7 --registry=https://registry.npmjs.org
      - name: Install NPM Packages
        run: npm install
      - name: Build Web-Application
        run: npm run build:web:prod
#      - name: Testing Web-Application (Engine)
#        run: npm run test:engine
#      - name: Testing Web-Application (Frontend)
#        run: npm run test:frontend