# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions

name: Continuous Deployment

on:
  release:
    type: [created]

jobs:
  continuous-integration:
    strategy:
      matrix:
        os: [macOS-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Update NPM
        run: npm install -g npm@7 --registry=https://registry.npmjs.org
      - name: Install NPM Packages
        run: npm install
      - name: Build Application
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy:app:prod
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: deploy