name: Create GitHub Release

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          fetch-depth: 1
#      - name: Install NodeJS
#        uses: actions/setup-node@v1
#        with:
#          node-version: 14.x
#      - name: Update NPM
#        run: npm install -g npm@7 --registry=https://registry.npmjs.org
#      - name: Install NPM Packages
#        run: npm install
#      - name: Build Application
#        run: npm run deploy:app:prod
      - name: Build Application (Dummy)
        run: mkdir ./deploy && touch ./deploy/hakuneko-win-x64.zip && touch ./deploy/hakuneko-osx-x64.dmg
      - name: Upload Release Builds
        uses: actions/upload-artifact@v2
        with:
          name: release-builds
          retention-days: 3
          path: deploy
      - name: Upload Release Templates
        uses: actions/upload-artifact@v2
        with:
          name: release-templates
          retention-days: 3
          path: .github/RELEASE_TEMPLATE/*.md
  publish:
    needs: build
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: |
          echo "DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "TAG=$(date -u +"%y%m%dT%H%M")" >> $GITHUB_ENV
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Dump Variables
        run: echo ${{ github.repository }}, ${{ github.ref }}
      - name: Dump Pre-Release Template
        run: cat ./release-templates/pre-release.md
      - name: Tag Release
        run: |
          echo $TAG
          curl -X POST -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/releases" -d '{"tag_name":"$TAG", "name":"canary • $DATE", "body":"Description..."}'
      - name: Upload Assets
        run: echo "$TAG • $DATE"